#ifndef INTERFACE_H
#define INTERFACE_H

#include "my_library.h"

#define INTERFACE_COMMAND_DEVICE_INFO (41)
#define INTERFACE_COMMAND_DEVICE_TOGGLE (42)
#define INTERFACE_COMMAND_DEVICE_TIME_SWITCH_MINIMUM (43)

#define INTERFACE_COMMAND_SENSOR_FLOW_INFO (61)
#define INTERFACE_COMMAND_SENSOR_FLOW_PULSES_PER_LITER (62)

#define INTERFACE_COMMAND_SENSOR_PRESSURE_INFO (121)

#define INTERFACE_COMMAND_CONTROL_IRRIGATION_INFO (81)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_INFO_ALL (82)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_START (83)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_STOP (84)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_DELIVER_VOLUME (85)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_DELIVER_TIME (86)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_GENERATOR_WAIT_TIME (87)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_PROGRAM_DURATION (88)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_CLEANING_GROUP3_DURATION (89)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_CLEANING_GROUP12_DURATION (90)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_IS_SEND_INFO (91)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_RESUME (92)
#define INTERFACE_COMMAND_CONTROL_IRRIGATION_IS_FAULTY_DETECTION_ACTIVE (93)

#define INTERFACE_COMMAND_CONTROL_IRRIGATION_TIME_INTERVAL_SEND_INFO (100LU) /* ms */

#define INTERFACE_COMMAND_CONTROL_SAFETY_RESET (101)

extern void interface_init(void);
extern void interface_process_data(void);
extern void interface_update(void);

/* interface serial */
extern void interface_serial_update(void);

#endif /* INTERFACE_H */
